version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/packages/ubuntu_localizations"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/ubuntu_logger"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/ubuntu_widgets"
    schedule:
      interval: "daily"
