name: xdg_icons
description: XDG theme icons for Flutter.
homepage: https://github.com/ubuntu-flutter-community/xdg_icons
repository: https://github.com/ubuntu-flutter-community/xdg_icons
issue_tracker: https://github.com/ubuntu-flutter-community/xdg_icons/issues
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  gtk_icon_theme:
    git:
      url: https://github.com/ubuntu-flutter-community/xdg_icons
      path: packages/gtk_icon_theme

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
