name: xdg_icons
description: XDG theme icons for Flutter.
homepage: https://github.com/jpnurmi/xdg_icons
repository: https://github.com/jpnurmi/xdg_icons
issue_tracker: https://github.com/jpnurmi/xdg_icons/issues
version: 0.0.1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  gtk_icon_theme:
    path: ../gtk_icon_theme

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
